### PR TITLE
results with SP w numActiveColumnsPerInhArea

### PR DESCRIPTION
**Pull request by breznak**
now the params are directly comparable to Numenta's.

### CODE REVIEW

**Comment by breznak** [comment]
FYI @steinroe this branch enables the old/new reintroduced param `numActiveColumnsPerInhArea`. 

Note: it needs the specific branch from htm.core.  

- currently it underperforms our "tuned" params with localAreaDensity option
- do you have somewhere what are the exact params for NumentaTM, Numenta detectors?

**Comment by psteinroe** [comment]
See htm-community/NAB/pull/28. Still underperforms though. I would propose we try to

- optimise on these too
- use the fake spatial anomaly detector Numenta used on both, the `localAreaDensity` version as well as the `numActiveColumnsPerInhArea` one to see if we can reach the NAB score numenta does.

What do you think?

EDIT: Or maybe go back to check wether NAB is working correctly?

**Comment by breznak** [comment]
> use the fake spatial anomaly detector Numenta used on both 

yes, let's do that first. That way we're as close to numenta as possible. 
- it just seems the `numActiveCols` is not a silver bullet (atleast w/o any work) 
- so we can't (again) say tuning params for either would bring us better scores 
- still need to decide if one is "biologically" better 
- :+1: for tuning both sets of params

**Comment by breznak** [comment]
Should we merge this branch into `fixing_...`? Both params can now be used. 
Currently localAreaDensity > numActiveCols

**Comment by psteinroe** [comment]
I would propose to merge it and then creating a new branch for adding the fake spatial anomaly detector, as its probably easier to work with 2 branches instead of 4 when running the optimisations.

**Comment by breznak** [comment]
> a new branch for adding the fake spatial anomaly detector 

Let's add that just as a commit as well, fake spAnomaly can be controlled with a toggle in the detector

**Comment by psteinroe** [comment]
are you working on adding the fake spAnomaly? otherwise I would do it 👍

**Comment by breznak** [comment]
> are you working on adding the fake spAnomaly? otherwise I would do it 

please go ahead. for a couple of hours I'll need to do sth else

**Pull request merged**
