### PR TITLE
Plot cleanup

### PR DESCRIPTION
**Pull request by breznak**
- [x] fix the issue with incorrect TP,FP in Plot
- [x] cleanup plot code

### CODE REVIEW

**Comment by breznak** [comment]
@Zbysekz can I have your review on this PR? I've addressed the issue with TP,TN we've talked about. And some cleanup. 
I've saved the files without figures, so the ipynb is much smaller. (and easier to diff later changes)

**Review by Zbysekz — CHANGES_REQUESTED** [review]
Nice changes. Good thing about the easier diff.
- In the second plot ( In[6] ) i can't see any data for "standard score", just the legend.
- The third plot ( In[7] ) shows just input value and input value mean? I would add some header comment on the beggining of In[7] to separate that
- Two first plots uses same data file that user can change at the beggining ("detector_summary_row") but third plot uses different data file?

**Comment by Zbysekz** [comment]
About the line in In[13] with comment "TODO is this branch needed?" i suggest to delete the condition and also the second branch with zero indexes index. Add this line instead: `assert summaryDataFrame["Threshold"][detector_summary_row].size==1, "There is multiple records in summary file for one datafile!"
`
I can't figure out why we would need to have multiple records per one datafile...

**Comment by breznak** [comment]
> Two first plots uses same data file that user can change at the beggining ("detector_summary_row") but third plot uses different data file? 

yes, the main modifications were to "Plot Results ..." file, while there was also a "Plot Data " which did just that, a single plot of the data file. I've decided to merge it just in a single file (?) 

> About the line in In[13] with comment "TODO is this branch needed?" i suggest to delete the condition and also the second branch with zero indexes index.[...] I can't figure out why we would need to have multiple records per one datafile...

I guess we can do that. I'd think it's for a compatibility with some older format, but currently NAB shouldn't change that much. I'll rm that

**Comment by breznak** [comment]
> In the second plot ( In[6] ) i can't see any data for "standard score", just the legend. 

thanks for spotting that. I've fixed the mistake I introduced and the data is being plotted. 
To be honest, I'm not sure about the meaning of that data and which block of code creates that. It's the 'NAB manually specified data of how anomaly score should go', and it shows -0.11 for non-anomaly etc. 
So we're again plotting that, but later we should look at how it's computed.

**Comment by breznak** [comment]
Thank you for your review, @Zbysekz  . Please re-review when you have time, I've adressed the issues.

**Review by Zbysekz — APPROVED** [review]
Good to go

**Review by Zbysekz — APPROVED** [review]

**Pull request merged**
